---
DOWN: 
  drop_table: 
    - acos
    - aros
    - aros_acos
    - members
    - groups
    - licenses
    - issues
    - issue_logs
UP: 
  create_table: 
    acos: 
      id: 
        type: integer
        null: false
        length: 11
        key: primary
        primary: id
      parent_id: 
        type: integer
        null: false
        length: 11
      model: 
        type: string
        null: false
        length: 64
      foreign_key: 
        type: integer
        null: false
        length: 11
      alias: 
        type: string
        default: 
        length: 128
      lft: 
        type: integer
        null: false
        length: 11
      rght: 
        type: integer
        null: false
        length: 11
    aros: 
      id: 
        type: integer
        null: false
        length: 11
        key: primary
        primary: id
      parent_id: 
        type: integer
        null: false
        length: 11
      model: 
        type: string
        default: 
        length: 64
      foreign_key: 
        type: integer
        null: false
        length: 11
      alias: 
        type: string
        default: 
        length: 128
      lft: 
        type: integer
        null: false
        length: 11
      rght: 
        type: integer
        null: false
        length: 11
    aros_acos: 
      id: 
        type: integer
        null: false
        length: 11
        key: primary
        primary: id
      aro_id: 
        type: integer
        null: false
        length: 11
      aco_id: 
        type: integer
        null: false
        length: 11
      _create: 
        type: integer
        null: false
        default: 0
        length: 2
      _read: 
        type: integer
        null: false
        default: 0
        length: 2
      _update: 
        type: integer
        null: false
        default: 0
        length: 2
      _delete: 
        type: integer
        null: false
        default: 0
        length: 2
    members: 
      id: 
        type: integer
        null: false
        length: 11
        key: primary
        primary: id
      group_id: 
        type: integer
        null: false
        length: 11
      username: 
        type: string
        null: false
        length: 64
      password: 
        type: string
        null: false
        length: 48
      user_status: 
        type: string
        null: false
        default: N
        length: 1
      created: 
        type: datetime
        null: false
      modified: 
        type: datetime
        null: false
    groups: 
      id: 
        type: integer
        null: false
        length: 11
        key: primary
        primary: id
      parent_id: 
        type: integer
        null: false
        length: 11
      name: 
        type: string
        null: false
        length: 64
    group_permissions: 
      id: 
        type: integer
        null: false
        length: 11
        key: primary
        primary: id
      parent_id: 
        type: integer
        null: false
        length: 11
      order: 
        type: integer
        null: false
        length: 11
      name: 
        type: string
        null: false
        length: 64
      description: 
        type: string
        null: true
        length: 255
      acos: 
        type: string
        null: false
        length: 255
    licenses: 
      id: 
        type: integer
        null: false
        default: 
        length: 11
        key: primary
        primary: id
      name_english: 
        type: string
        null: true
        default: 
      name_chinese: 
        type: string
        null: true
        default: 
      license: 
        type: string
        null: true
        default: 
    issues: 
      id: 
        type: integer
        null: false
        default: 
        length: 11
        key: primary
        primary: id
      license_id: 
        type: string
        null: true
        default: 
      license_uuid: 
        type: string
        null: true
        default: 
      info_source: 
        type: string
        null: true
        default: 
      status: 
        type: string
        null: true
        default: 
      name_english: 
        type: string
        null: true
        default: 
      name_chinese: 
        type: string
        null: true
        default: 
      license: 
        type: string
        null: true
        default: 
      dosage_form: 
        type: string
        null: true
        default: 
      dosage: 
        type: string
        null: true
        default: 
      batch_no: 
        type: string
        null: true
        default: 
      pic_old: 
        type: string
        null: true
        default: 
      pic_new: 
        type: string
        null: true
        default: 
      label_old: 
        type: string
        null: true
        default: 
      label_old_file: 
        type: string
        null: true
        default: 
      label_new: 
        type: string
        null: true
        default: 
      label_new_file: 
        type: string
        null: true
        default: 
      evidence: 
        type: string
        null: true
        default: 
      modified: 
        type: string
        null: true
        default: 
      modified_by: 
        type: string
        null: true
        default: 
    issue_logs: 
      id: 
        type: integer
        null: false
        default: 
        length: 11
        key: primary
        primary: id
      issue_id: 
        type: string
        null: true
        default: 
      status: 
        type: string
        null: true
        default: 
      comment: 
        type: string
        null: true
        default: 
      created: 
        type: string
        null: true
        default: 
      created_by: 
        type: string
        null: true
        default: 
